### ISSUE TITLE
Fatal error when activating

### ISSUE THREAD

**Issue by eurobank** [LeoColomb/wp-auto-links#3]
Any ideas ?

Warning: require_once(/home/wp-content/plugins/wp-auto-links-master/vendor/autoload.php): failed to open stream: No such file or directory in /home/wp-content/plugins/wp-auto-links-master/wp-auto-links.php on line 19

**Comment by LeoColomb** [comment]
Thanks for opening this issue @eurobank.

How did you install the extension?

**Comment by eurobank** [comment]
Maybe it is cause by missing some object caching (i thought W3TC was enough).

Is that it the cause ?

I have installed as all plugins.

**Comment by LeoColomb** [comment]
> I have installed as all plugins.

Can you elaborate? From the WordPress Plugin site?

**Comment by eurobank** [comment]
No from here. I can't find it on WP site.

**Comment by LeoColomb** [comment]
Oh, but you need to follow instruction on the README: https://github.com/LeoColomb/wp-auto-links#installation

* Via [Composer](https://getcomposer.org/) (recommended)
  ```bash
  composer require leocolomb/wp-auto-links
  ```

* Via [WordPress Plugins](https://wordpress.org/plugins/wp-auto-links/)
